### ISSUE TITLE
Callback bulk_user_actions Deprecated

### ISSUE THREAD

**Issue by waleedhassan5** [catalyst/moodle-tool_emailutils#50]
Callback bulk_user_actions in tool_emailutils component should be migrated to new hook callback for core_user\hook\extend_bulk_user_actions
Got this while creating a new user manually.

**Comment by danmarsden** [comment]
Thanks @waleedhassan5 - if you have internal development capabilities, feel free to help further by submitting a pull request - it may be some time before we do this on our end.
