### ISSUE TITLE
Task tool_emailutils\task\update_suppression_list should gracefully fail if not configured

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_emailutils#53]
Currently it throws and exception which makes the task to fail. Here https://github.com/catalyst/moodle-tool_emailutils/commit/8b566ebc2b25f6162789d8dce1cf8576c630d14f#diff-7fdb524064d4e2b7d1abbf3cea6a6589a24dc23955fb9271da46c1646c318a67R134

Should be just mtrace or debugging.

**Comment by brendanheywood** [comment]
I don't think it should even get this far, if its not enabled it simple should not run at all and there should be zero debugging noise. Only if it is enabled should it emit noise if it can't connect, and it should also declare a status check if it can or cannot connect.

**Comment by dmitriim** [comment]
Yes sure. No point to pollute logs if not enabled.

**Comment by marxjohnson** [comment]
Sorry about that, Waleed is picking this up.
